### ISSUE TITLE
pod does not load the latest Swift 3 compatible version

### ISSUE THREAD

**Issue by ujikol** [xaviermerino/XMSegmentedControl#27]

**Comment by sofbix** [comment]
+1

**Comment by bluemix** [comment]
same here

**Comment by xaviermerino** [comment]
Hey guys, thanks for letting me know. I'll fix this soon. Im just in the middle of midterms and I haven't had the time to fix this. As of now a fresh copy of XMSegmentedControl.swift will have all of the Swift 3 syntax changes done. Let me know how that works! Thanks for your feedback.

**Comment by carsonaberle** [comment]
Any word on this? I'm still not getting the swift 3 version

**Comment by dbburgess** [comment]
The `master` branch has been updated with Swift 3 support, @xaviermerino just hasn't released a new version. You can use the latest from `master` by changing the reference in your `Podfile` to this:

```ruby
pod 'XMSegmentedControl', :git => 'https://github.com/xaviermerino/XMSegmentedControl.git'
```

**Comment by andre991** [comment]
+ 1
