### ISSUE TITLE
Is there any support for swift 3?

### ISSUE THREAD

**Issue by headstream12** [xaviermerino/XMSegmentedControl#37]
After the renovation of the pods, the project does not want to assemble. Swears at the old syntax in the source library. Tell me what to do?

**Comment by xaviermerino** [comment]
Try this. It will load the one on the master branch which has support for Swift 3.

```
pod 'XMSegmentedControl', :git => 'https://github.com/xaviermerino/XMSegmentedControl.git'
```

**Comment by xaviermerino** [comment]
Did this fix the issue? Please let me know.

**Comment by aschzero** [comment]
@xaviermerino I had the same issue and updating my Podfile with that line fixed it.

**Comment by xaviermerino** [comment]
@aschaper Thanks for letting me know. I'll close this issue for now.
